---
deployment:
  tasks:
    - export REPOPATH=/home/fzthasancelik/repositories/fzthasancelik/
    - export DEPLOYPATH=/home/fzthasancelik/public_html/
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='wp-config.php' --exclude='wp-content/uploads' --exclude='error_log' --exclude='*.zip' $REPOPATH $DEPLOYPATH