---
deployment:
  tasks:
    - export REPOPATH=/home/fzthasancelik/repositories/fzthasancelik/
    - export DEPLOYPATH=/home/fzthasancelik/public_html/
    - /bin/echo "Deploy started $(date)" > $DEPLOYPATH/deploy-cpanel-log.txt
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='wp-config.php' --exclude='wp-content/uploads' --exclude='error_log' --exclude='*.zip' $REPOPATH $DEPLOYPATH >> $DEPLOYPATH/deploy-cpanel-log.txt 2>&1
    - /bin/echo "Deploy finished $(date)" >> $DEPLOYPATH/deploy-cpanel-log.txt